services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    depends_on:
      - postgres
    mem_limit: 512m
    mem_reservation: 256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  node:
    image: node:22-bullseye
    ports:
      - "5173:5173"
    volumes:
      - ./src:/src
    command: ["sleep", "infinity"]
    working_dir: /src

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # 手動停止以外は自動再起動
    restart: unless-stopped

volumes:
  postgres_data:
