
name: Weekly Rector

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rector:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      has_changes: 'false'
    steps:
      # schedule 実行時は main ブランチを checkout
      - uses: actions/checkout@v4
        if: github.event_name == 'schedule'
        with:
          ref: main
      # 手動実行時は選択されたブランチを checkout
      - uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ github.ref_name }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/composer
          key: ${{ runner.os }}-composer-${{ hashFiles('server/composer.lock') }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction
        working-directory: ./src

      - name: Run Rector
        run: composer rector
        working-directory: ./src

      - name: Check for changes
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git add .
          git diff --cached --quiet || echo "has_changes=true" >> "$GITHUB_ENV"

      - name: Generate timestamp
        # id`を付けておくと後続のステップでsteps.<id>.outputs.<key>のように参照可能
        id: timestamp
        if: env.has_changes == 'true'
        run: echo "stamp=refactor/weekly-rector-$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        if: env.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: apply rector fixes"
          title: "Refactor: weekly-rector/${{ steps.timestamp.outputs.stamp }}"
          body: |
            毎週月曜の9時に定期実行されるRectorによるコードのリファクタリングです。
            GitHub Actionsで静的解析と自動テストを行い、PASSすることを確認してからマージしてください。
          branch: ${{ steps.timestamp.outputs.stamp }}
